# -*- coding: utf-8 -*-
"""NikeProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sPTsqZq_Q6aPaPAMe6Rd5ghLWrDlNyKj
"""

import pandas as pd
import numpy as np

# Load the data
df = pd.read_csv("global_nike_under_50mb.csv")
print("Initial DataFrame shape:", df.shape)
initial_duplicates_count = df.duplicated().sum()
print("Initial duplicates found:", initial_duplicates_count)

# Drop specified columns
columns_to_drop = ["size_count", "available_size_count", "gtin", "employee_price"]
df = df.drop(columns=columns_to_drop)
print("DataFrame shape after dropping columns:", df.shape)

# Remove duplicates from the DataFrame (which now has columns dropped)
df_cleaned = df.drop_duplicates(keep="first")
print("Final cleaned DataFrame shape (after column drop and duplicate removal):", df_cleaned.shape)
duplicates_removed = df.shape[0] - df_cleaned.shape[0]
print("Number of duplicates removed during cleaning:", duplicates_removed)

# If you intend to continue working with the fully cleaned DataFrame as 'df', you can reassign it:
df = df_cleaned

df_cleaned.to_csv('global_nike_cleaned.csv', index=False)
print('Cleaned data saved to global_nike_cleaned.csv')

"""The `index=False` argument prevents pandas from writing the DataFrame index as a column in the CSV file.

If you want to save this file persistently and share it, consider saving it to your Google Drive after mounting it in Colab. You can also download the file directly from the Colab file browser (folder icon on the left sidebar).
"""



