# -*- coding: utf-8 -*-
"""NikeProject2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iXHWb6n5MMx9bBhN_jxia4HCDOif1A1-
"""

import pandas as pd
df= pd.read_csv("global_nike.csv")
df.shape
df.head()

df["product_name_eng"] = df["product_name"]
df["subcategory_en"] = df["subcategory"]
df["color_name_en"] = df["color_name"]

#!pip install deep_translator
#from deep_translator import GoogleTranslator

#creating translating function
#translator = GoogleTranslator(source='ja', target='en')
#def translate_text(text):
 #   if pd.isna(text):
  #      return text

   # try:
    #    return translator.translate(str(text))
    #except:
     #   return text

#product_translations = {}

#for text in df["product_name"].dropna().unique():
 #   if any('\u3040' <= char <= '\u30ff' or '\u4e00' <= char <= '\u9fff' for char in str(text)):
  #      product_translations[text] = translate_text(text)

!pip install -q transformers sentencepiece torch tqdm

import torch
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
model_name = "Helsinki-NLP/opus-mt-ja-en"

device = "cuda" if torch.cuda.is_available() else "cpu"

print("Using:", device)

tokenizer = AutoTokenizer.from_pretrained(model_name)

model = AutoModelForSeq2SeqLM.from_pretrained(model_name)
model = model.to(device)

import re

def contains_japanese(text):
    if pd.isna(text):
        return False

    text = str(text)

    japanese_pattern = r'[\u3040-\u30ff\u3400-\u4dbf\u4e00-\u9fff]'

    return bool(re.search(japanese_pattern, text))

from tqdm.auto import tqdm

def translate_batch(texts, batch_size=32):

    results = []

    for i in tqdm(range(0, len(texts), batch_size)):

        batch = texts[i:i + batch_size]

        inputs = tokenizer(
            batch,
            return_tensors="pt",
            padding=True,
            truncation=True,
            max_length=128
        ).to(device)

        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_length=128
            )

        translations = tokenizer.batch_decode(
            outputs,
            skip_special_tokens=True
        )

        results.extend(translations)

    return results

# Get unique product names
product_values = df["product_name"].dropna().astype(str).unique()

# Keep only values containing Japanese
japanese_products = [
    x for x in product_values
    if contains_japanese(x)
]

print("Unique product names:", len(product_values))
print("Japanese product names:", len(japanese_products))

product_translations = translate_batch(
    japanese_products,
    batch_size=32
)

product_translation_dict = dict(
    zip(japanese_products, product_translations)
)

df["product_name_en"] = df["product_name"].map(
    lambda x: product_translation_dict.get(str(x), x)
    if pd.notna(x) else x
)
df[["product_name", "product_name_en"]].sample(20)

subcategory_values = df["subcategory"].dropna().astype(str).unique()

japanese_subcategories = [
    x for x in subcategory_values
    if contains_japanese(x)
]

print("Total unique subcategories:", len(subcategory_values))
print("Japanese subcategories:", len(japanese_subcategories))

subcategory_translations = translate_batch(
    japanese_subcategories,
    batch_size=32
)

subcategory_translation_dict = dict(
    zip(japanese_subcategories, subcategory_translations)
)

df["subcategory_en"] = df["subcategory"].map(
    lambda x: subcategory_translation_dict.get(str(x), x)
    if pd.notna(x) else x
)

df[["subcategory", "subcategory_en"]].sample(20)

color_values = df["color_name"].dropna().astype(str).unique()

japanese_colors = [
    x for x in color_values
    if contains_japanese(x)
]

print("Total unique colors:", len(color_values))
print("Japanese colors:", len(japanese_colors))

color_translations = translate_batch(
    japanese_colors,
    batch_size=32
)

color_translation_dict = dict(
    zip(japanese_colors, color_translations)
)

df["color_name_en"] = df["color_name"].map(
    lambda x: color_translation_dict.get(str(x), x)
    if pd.notna(x) else x
)

df[["color_name", "color_name_en"]].sample(20)

df[
    [
        "product_name",
        "product_name_en",
        "subcategory",
        "subcategory_en",
        "color_name",
        "color_name_en"
    ]
].sample(30)

print("Japanese remaining in product_name_en:",
      df["product_name_en"].apply(contains_japanese).sum())

print("Japanese remaining in subcategory_en:",
      df["subcategory_en"].apply(contains_japanese).sum())

print("Japanese remaining in color_name_en:",
      df["color_name_en"].apply(contains_japanese).sum())

df.to_csv('global_nike_translated2.csv', index=False)
print('Translated data saved to global_nike_translated2.csv')