# -*- coding: utf-8 -*-
"""NikeProject3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iZx4OjRbtB041wN2PMvBmwo_gxBDy9Ay
"""

import pandas as pd
df = pd.read_csv("Book2.csv")
df.head()

exchange_rates = {
    'USD': 1,
    'EUR': 1.08,
    'GBP': 1.27,
    'JPY': 0.0067
}

df['sale_usd'] = df['sale'] * df['currency'].map(exchange_rates)

#columns_to_drop = ['subcategory','product_name','product_name_eng','color_name']
#df = df.drop(columns=columns_to_drop)
print("DataFrame shape after dropping columns:", df.shape)
df.head()

#columns_to_drop = ['sales']
#df = df.drop(columns=columns_to_drop)
print("DataFrame shape after dropping columns:", df.shape)
df.head()

def get_product_type(text):
    if pd.isna(text):
        return "Other"

    text = str(text).lower()

    # SHOES
    if any(word in text for word in ["shoe","shoes","sneaker","sneakers","trainer","trainers","boot","boots",
        "slides","sandal","sandals"]):
        return "Shoes"

    # CLOTHING
    elif any(word in text for word in ["shirt","t-shirt","tee","top","hoodie","jacket","pants","shorts",
        "leggings","bra","dress","jersey","sweatshirt","coat","skirt","tank"
    ]):
        return "Clothing"

    # ACCESSORIES
    elif any(word in text for word in ["bag","backpack","cap","hat","socks","watch","wallet"
    ]):
        return "Accessories"

    # EQUIPMENT
    elif any(word in text for word in [
        "ball","equipment"
    ]):
        return "Equipment"

    # GOLF
    elif any(
        word in text
        for word in ["golf","polo","cleat","cleats","tour","dry-fit golf","tiger woods","jordan golf",
        ]
    ):
        return "Golf"

    # SKATEBOARDING
    elif any(
        word in text
        for word in ["skate", "skateboarding", "sb", "janoski", "nyjah", "ishod"]
    ):
        return "Skateboarding"

    # FOOTBALL
    elif any(
        word in text
        for word in ["football","soccer", "mercurial","phantom","tiempo","superfly","f.c.","fc","jersey",
            "pitch","academy","strikers",
        ]
    ):
        return "Football"

    # RUNNING
    elif any(
        word in text
        for word in ["run","running","runner","pegasus","vaporfly","alphafly","invincible","vomero",
            "structure","infinity","marathon","free rn","miler",
        ]
    ):
        return "Running"

    # TRAINING
    elif any(
        word in text
        for word in ["train","training","trainer","gym","workout","metcon","fitness","cross training",
            "hiit","legend","flex",
        ]
    ):
        return "Training"

    # LIFESTYLE
    elif any(
        word in text
        for word in ["lifestyle","casual","streetwear","force","air max","dunk","blazer","jordan","sportswear",
            "nsw","essential","classic","heritage","everyday",
        ]
    ):
        return "Lifestyle"

    # EVERYTHING ELSE
    else:
        return "Other"

df.to_csv('cleaned_4.csv', index=False)
print('Translated data saved to cleaned_4.csv')

def create_clean_subcategory(row):

    gender_clean = str(row["gender_clean"]).strip().lower()
    product_type = row["product_type"]

    # Standardize gender labels
    if gender_clean in ["male", "men", "mens", "men's"]:
        gender_label = "Men's"

    elif gender_clean in ["female", "women", "womens", "women's"]:
        gender_label = "Women's"

    elif gender_clean in ["kid", "kids", "children", "child"]:
        gender_label = "Kids"

    elif gender_clean in ["unisex"]:
        gender_label = "Unisex"

    else:
        gender_label = "Unisex"

    return f"{gender_label} {product_type}"

df["product_type"] = df["product_name_en"].apply(get_product_type)
df["clean_subcategory"] = df.apply(
    create_clean_subcategory,
    axis=1
)

df[
    [
        "subcategory_en",
        "gender_clean",
        "product_type",
        "clean_subcategory"
    ]
].sample(30)

df["clean_subcategory"].value_counts()

df["clean_subcategory"].nunique()

df.to_csv('Nike_cleaned.csv', index=False)
print('Translated data saved to Nike_cleaned.csv')